INSERT INTO PARTIER VALUES (DEFAULT, 'Socialdemokratiet');
INSERT INTO PARTIER VALUES (DEFAULT, 'Det Konservative Folkeparti');
INSERT INTO PARTIER VALUES (DEFAULT, 'SF - Socialistisk Folkeparti');
INSERT INTO PARTIER VALUES (DEFAULT, 'Dansk Folkeparti');
INSERT INTO PARTIER VALUES (DEFAULT, 'Venstre, Danmarks Liberale Parti');
INSERT INTO PARTIER VALUES (DEFAULT, 'Enhedslisten - De Rød-Grønne');

INSERT INTO KANDIDATER VALUES (DEFAULT, 491, 'Meijer', 'Marcel', 1);
INSERT INTO KANDIDATER VALUES (DEFAULT, 48, 'Kristensen', 'Michael', 1);
INSERT INTO KANDIDATER VALUES (DEFAULT, 44, 'Hansen', 'Helle', 1);
INSERT INTO KANDIDATER VALUES (DEFAULT, 45, 'Knobelauch', 'Karina', 1);
INSERT INTO KANDIDATER VALUES (DEFAULT, 35, 'Hafstein Wolffbrandt', 'Stefan', 1);

INSERT INTO KANDIDATER VALUES (DEFAULT, 333, 'Per', 'Urban Olsen', 2);
INSERT INTO KANDIDATER VALUES (DEFAULT, 41, 'Askjær', 'Peter', 2);
INSERT INTO KANDIDATER VALUES (DEFAULT, 29, 'Sørensen', 'Martin', 2);
INSERT INTO KANDIDATER VALUES (DEFAULT, 12, 'Bramstorp', 'Louise', 2);
INSERT INTO KANDIDATER VALUES (DEFAULT, 36, 'Jensen', 'Sigfred', 2);

INSERT INTO KANDIDATER VALUES (DEFAULT, 261, 'Holm', 'Ulla', 3);
INSERT INTO KANDIDATER VALUES (DEFAULT, 28, 'Bønkel', 'Kjeld', 3);
INSERT INTO KANDIDATER VALUES (DEFAULT, 9, 'Olsen', 'Anne Grethe', 3);
INSERT INTO KANDIDATER VALUES (DEFAULT, 10, 'Krag', 'Lone', 3);
INSERT INTO KANDIDATER VALUES (DEFAULT, 1, 'Buur', 'Børge S.', 3);

INSERT INTO KANDIDATER VALUES (DEFAULT, 21, 'Mortensen', 'Per', 4);

INSERT INTO KANDIDATER VALUES (DEFAULT, 310, 'Wiese', 'Søren', 5);
INSERT INTO KANDIDATER VALUES (DEFAULT, 140, 'Olesen', 'Anita Elgaard Højholt', 5);
INSERT INTO KANDIDATER VALUES (DEFAULT, 88, 'Bruun', 'Carsten', 5);
INSERT INTO KANDIDATER VALUES (DEFAULT, 22, 'Exner', 'Mogens', 5);
INSERT INTO KANDIDATER VALUES (DEFAULT, 23, 'Guldborg', 'Anja', 5);

INSERT INTO KANDIDATER VALUES (DEFAULT, 43, 'Mc Quaid', 'Katrine Høegh', 6);
INSERT INTO KANDIDATER VALUES (DEFAULT, 27, 'Søgaard', 'Jette M.', 6);
INSERT INTO KANDIDATER VALUES (DEFAULT, 1, 'Caspersen', 'Søren', 6);
INSERT INTO KANDIDATER VALUES (DEFAULT, 5, 'Birkmand', 'Pia', 6);






