INSERT INTO PARTIER VALUES (DEFAULT, 'Socialdemokratiet');
INSERT INTO PARTIER VALUES (DEFAULT, 'Det Konservative Folkeparti');
INSERT INTO PARTIER VALUES (DEFAULT, 'SF - Socialistisk Folkeparti');
INSERT INTO PARTIER VALUES (DEFAULT, 'Dansk Folkeparti');
INSERT INTO PARTIER VALUES (DEFAULT, 'Venstre, Danmarks Liberale Parti');
INSERT INTO PARTIER VALUES (DEFAULT, 'Enhedslisten - De Rød-Grønne');

INSERT INTO KANDIDATER VALUES (DEFAULT, 100, 'losang', 'jimmy', 1);
INSERT INTO KANDIDATER VALUES (DEFAULT, 150, 'losang', 'jimmy', 1);
INSERT INTO KANDIDATER VALUES (DEFAULT, 200, 'losang', 'jimmy', 2);
INSERT INTO KANDIDATER VALUES (DEFAULT, 300, 'losang', 'jimmy', 3);
INSERT INTO KANDIDATER VALUES (DEFAULT, 400, 'losang', 'jimmy', 4);
INSERT INTO KANDIDATER VALUES (DEFAULT, 500, 'losang', 'jimmy', 5);

